### PR TITLE
Add Drupal 10 recipe

### PR DESCRIPTION
**Pull request by gitressa**
To Do:
- [ ] Create https://docs.lando.dev/config/drupal10.html
- [x] ~~Check if downloading https://ftp.drupal.org/files/projects/drupal-10.0.x-dev.tar.gz in https://github.com/lando/drupal/blob/main/examples/drupal10/README.md file followed by `composer install` works, since it is not a complete tar-ball, out of the box. For more, see https://www.drupal.org/project/drupal/releases/9.4.x-dev and https://www.drupal.org/project/drupal/releases/10.0.x-dev~~
^^ The https://www.drupal.org/project/drupal/releases/10.0.x-dev page has since been completed, and now serve a full tar-ball, in stead of just `composer.*` files.

### CODE REVIEW

**Comment by labboy0276** [comment]
@gitressa is this PR good to go to merge in?

**Comment by gitressa** [comment]
@labboy0276 I have tried to create a local instance, and based on https://github.com/lando/drupal#development I cloned and checked out the Merge Request (#3) with this:

```
git clone https://github.com/lando/drupal.git && cd drupal
git fetch origin pull/3/head:d10
git checkout d10 
yarn install
```

Is there a command which compiles and runs this updated Lando, so I can check if `drupal10` is included under available recipes?

**Comment by labboy0276** [comment]
@gitressa the testing here can do that for you, but you can pull lando from source and update the yarn plugin package locally.  

Can you add drupal10 to this file: https://github.com/lando/drupal/blob/main/.github/workflows/pr-drupal-tests.yml ?

then it should be good to go

**Comment by gitressa** [comment]
@labboy0276 Sounds great, I have added `drupal10` to the file you asked for.

About building a local instance by pulling Lando from source and updating the yarn plugin package locally, is there a page with the steps that I can follow? Or perhaps you can quickly dump the commands here?

Also, we should remember the two To-Do's :)

**Comment by labboy0276** [comment]
@gitressa If you want to check out this doc: https://docs.lando.dev/contrib/contrib-plugins.html it explains the plugin structure and what to do for the most part.

When we are doing plugin dev, it is best to symlink to your local repo, you can see how I do it here:

```
john@tandem:~/.lando/plugins/@lando$ ls -la
total 8
drwxrwxr-x 2 john john 4096 Jan 28 10:22 .
drwxrwxr-x 3 john john 4096 Jan  3 09:59 ..
lrwxrwxrwx 1 john john   23 Jan 11 09:19 drupal -> /home/john/lando/drupal
lrwxrwxrwx 1 john john   21 Jan 28 10:22 mean -> /home/john/lando/mean
```

Then do a `lando config --clear` and you can check if it is pointing to your local via `lando config --path plugins`

**Comment by gitressa** [comment]
Thanks @labboy0276 your tips helped a lot, and I managed to test the plugin locally with these steps:

1. Download the Drupal recipe, check out this Merge Request and build it with yarn
```
git clone https://github.com/lando/drupal
cd drupal
git fetch origin pull/3/head:d10
git checkout d10 
yarn install
```
2. Create the plugin folder, symlink to the drupal recipe above, clear cache and check it is registered
```
mkdir ~/.lando/plugins
cd ~/.lando/plugins/
ln -s ~/drupal
lando config --clear
lando config --path plugins | grep drupal
```
I could now create a Drupal 10 instance, so it seems to work as expected.

Also, since I created this issue, the https://www.drupal.org/project/drupal/releases/10.0.x-dev page has been completed, and now serve a full tar-ball, in stead of just `composer.*` files.

**Comment by labboy0276** [comment]
@gitressa looks good to me, I will merge this in.  If you wan tot create a PR for the docs here: https://github.com/lando/docs

**Comment by gitressa** [comment]
Great, thanks. Do you mean creating the https://docs.lando.dev/config/drupal10.html page?

**Comment by labboy0276** [comment]
@gitressa yes

**Comment by gitressa** [comment]
@labboy0276 I have created a documentation page for Drupal 10, and created a Merge Request https://github.com/lando/docs/pull/185.

**Pull request merged**
