### PR TITLE
Updated installation of Drupal 9/10 via Composer

### PR DESCRIPTION
**Pull request by HarishSTOnline**
The current doc rely on installing Drupal via zip file. But the recommended method is via Composer.
This commit updates the docs to use composer for installing Drupal.

### CODE REVIEW

**Comment by reynoldsalec** [comment]
Thanks @HarishSTOnline!

**Comment by HarishSTOnline** [comment]
@gitressa I am not sure if you misunderstood this. 
I understand `composer create-project` doesn't work on non-empty directory. But this update doesn't need you to start lando (lando start) before running `composer create-project` command. 

We are basically creating the project with composer in a temp directory and then moving the application code back into root directory. Please confirm if the code is moved to root directory before going forward with `lando start`.
Checkout the Symfony recipe for a similar approach being documented.

Meanwhile, let me try creating a project again and update the findings.

**Comment by HarishSTOnline** [comment]
Thanks buddy for the quick update! Happy that it helps!

**Comment by HarishSTOnline** [comment]
Sure, I'll check that out when I get some free time! Thanks!

**Comment by HarishSTOnline** [comment]
I've added an approval review for one of the pull request. It needs a approving review from maintainers though.

**Pull request merged**
